### ISSUE TITLE
Design files for side panels

### ISSUE THREAD

**Issue by G33KatWork** [Jana-Marie/laemp#2]
Could you please add the design files for the bigger LÄMP with the side panels as [shown here](https://github.com/Jana-Marie/laemp/tree/main/design/img)? 👉👈🥺

... or point me at them. I couldn't find them in the repo

**Comment by Jana-Marie** [comment]
OwO Did I really forget to push it. Will fix asap

**Comment by Jana-Marie** [comment]
https://github.com/Jana-Marie/laemp/tree/main/3D :3

**Comment by Jana-Marie** [comment]
Oh wow, I cannot read. Yes, let me push them as well

**Comment by Jana-Marie** [comment]
https://github.com/Jana-Marie/LAEMP-Obelisk

**Comment by Jana-Marie** [comment]
https://github.com/Jana-Marie/LAEMP-Prism

**Comment by Jana-Marie** [comment]
Thank you for opening this issue, it lead to me doing a full repo cleanup and writeup :3

**Comment by G33KatWork** [comment]
Thank you! Time to build some and make my office pretty :)
